[package]
name = "strava-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["client", "full"] }
hyper-tls = "0.5.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
termion = "2.0.1"
tokio = { version = "1.24.2", features = ["full"] }
url = "2.3.1"
xdg = "2.4.1"
