name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint and test
      run: make
    - name: Build
      run: |
        cargo sqlx database create
        cargo sqlx migrate run
        export DATABASE_URL=sqlite://strava.sqlite
        cargo build --release --locked
