name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://strava.sqlite

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint and test
      run: |
        cargo build -p sqlx
        cargo sqlx database create
        cargo sqlx migrate run
        make
    - name: Build
      run: |
        cargo build --release --locked
